default["tools"]["packages"] = [
	"apt-file",
	"virtualbox-nonfree",
	"meld",
	"vim",
	"subversion",
	"rubygems",
	"calibre",
	"wireshark",
	"openconnect",
	"network-manager-openconnect-gnome",
	"xvfb",
	"balance",
	"python-nose",
	"python-setuptools",
	"libyaml-dev",
	"python-pip",
	"python-dev",
	"libasound2-plugins:i386",
	"mysql-workbench",
	"sshfs",
	"libxslt-dev",
	"libxml2-dev",
	"libvirt-dev",
	"libvirt-bin",
	"xen-utils-common",
	"xcp-xe",
	"stunnel",
	"hplip-gui",
	"libjna-java"
]

default["tools"]["deb_packages"] = [
	"vagrant_1.2.2_x86_64",
	"google-chrome-stable_current_amd64",
	"skype-ubuntu-precise_4.2.0.11-1_i386"
]

default["tools"]["scripts"] = [
	"aduserdump",
	"admodify",
	"adgroups",
	"backup",
	"dbcreate",
	"dbicreate",
	"dbiedit",
	"mount_rsync",
	"rolecreate",
	"roleedit",
	"rsync_quota",
	"vpn_route",
	"vpn_route_wireless",
	"mcsdestroy",
	"mcsresume",
	"mcsstart",
	"mcsstop",
	"mcssuspend",
	"mcsup"
]
